version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - './:/app'
      - '/app/node_modules'
    environment:
      - PORT
      - BASE_URL
    ports:
      - "${PORT}:4200"
