version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - PORT
      - BASE_URL
      - PROD_PORT
    ports:
      - "${PROD_PORT}:80"